version: '3.8'

services:
  nextapp:
    container_name: nextapp
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    working_dir: /app
    command: "npm run dev"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge